workflows:
  expo-ios-build:
    name: Expo iOS Build
    environment:
      node: 18
    scripts:
      - npm install
      - npm install -g eas-cli
      - eas --version
      - eas build --platform ios --non-interactive
    artifacts:
      - build/ios/**/*.ipa
